### ISSUE TITLE
`unsupported` folder

### ISSUE THREAD

**Issue by KindDragon** [bilke/conan-eigen3#1]
Please add Eigen unsupported folder to package

**Comment by JPGygax68** [comment]
I'd like to second that request. Right now, unsupported parts can be accessed like this:
```
#include <unsupported/Eigen/OpenGLSupport>
```
but it would be much nicer if we didn't have to prefix the path with `unsupported`.

I believe the following change to `conanfile.py` should do the trick (unverified!):
```
   def package_info(self):
        self.cpp_info.includedirs = ['.', './unsupported'] 
```

**Comment by bilke** [comment]
`unsupported`-folder was added with 051d9927cf96c76fdd491c7a7b2cdff0f7866ee8.

**Comment by JPGygax68** [comment]
Yes, the `unsupported` folder is being copied, but is really intended to be specified explicitly when doing `#include ...` ?

**Comment by bilke** [comment]
I have made your proposed change in 32810270fc2cc1b61842493ddd32afc0062c1662. Thanks!
